# config.yaml
training:
  TU: 3                 # 정책 업데이트 주기
  TC: 5                 # 타겟 네트워크 업데이트 주기
  TR: 50                # Shrink & Perturb 주기
  map_reset_interval: 50 # 맵 변경 주기
  replay_ratio: 10       # Replay Ratio
  episodes: 800          # 총 에피소드 수
  alpha: 0.9             # Shrink & Perturb 비율
  save_point: 50         # 모델 저장 간격

environment:
  env_count: 4           # 병렬 환경 수